comment_width = 120
control_brace_style = "ClosingNextLine"
error_on_line_overflow = false
error_on_unformatted = false
match_block_trailing_comma = true
max_width = 120
reorder_imported_names = false
struct_lit_single_line = true
