language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --all
  - cargo run --verbose --example runtest
  - cargo test --verbose --features "test" --all
matrix:
  allow_failures:
    - rust: beta
    - rust: nightly
