language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

before_script:
  # Workaround for bug in piston_window caused by mesa being out of date
  # From: https://github.com/PistonDevelopers/piston/issues/1202#issuecomment-338331123
  - |
    if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
        pip install --user mako
        git clone https://anongit.freedesktop.org/git/mesa/mesa.git
        cd mesa
        git checkout mesa-17.1.9
        ./autogen.sh --prefix=/path/to/desired/mesa-inst --with-gallium-drivers="i915,swrast" --with-dri-drivers="i915,i965,swrast"
        make -j 8
        make install
    fi

  # We are using xvfb to run our runtest which uses GUI
  # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then export DISPLAY=:99.0; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sh -e /etc/init.d/xvfb start; fi
  # give xvfb some time to start
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sleep 3; fi

script:
  - cargo build --verbose --all
  - cargo run --verbose --example runtest
  - cargo test --verbose --features "test" --all
  - cargo doc --verbose --all
matrix:
  # Mark the build as finished even if the allow_failures builds
  # are still running
  fast_finish: true
  allow_failures:
    - rust: beta
    - rust: nightly
