language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --all
  # Make sure we can run on osx
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cargo run --verbose --example runtest; fi
  - cargo test --verbose --features "test" --all
  - cargo doc --verbose --all
matrix:
  # Mark the build as finished even if the allow_failures builds
  # are still running
  fast_finish: true
  allow_failures:
    - rust: beta
    - rust: nightly
