[package]
name = "turtle"
version = "1.0.0-alpha.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
description = "Turtle Graphics in Rust"
homepage = "http://turtle.rs"
repository = "https://github.com/sunjay/turtle"
readme = "README.md"
keywords = ["turtle", "graphics", "drawing", "teaching", "beginner"]
# crates.io/category_slugs
categories = ["rendering", "rendering::graphics-api", "rendering::engine", "games", "gui"]
license = "MIT"

[dependencies]
piston_window = "^0.73.0"
interpolation = "^0.1.0"
fps_clock = "^2.0.0"
rand = "^0.3.17"
