[package]
name = "turtle"
version = "0.0.0"
authors = ["Sunjay Varma <varma.sunjay@gmail.com>"]
description = "Turtle Graphics in Rust"
repository = "https://github.com/sunjay/turtle"
readme = "README.md"
keywords = ["turtle", "turtle", "drawing", "teaching", "learning", "beginners"]
# crates.io/category_slugs
categories = ["rendering", "rendering::graphics-api", "rendering::engine", "games", "gui"]
license = "MIT"

[dependencies]
piston_window = "*"
interpolation = "*"
fps_clock = "*"
